### ISSUE TITLE
Sometime uses float notation for large integers

### ISSUE THREAD

**Issue by nboley** [dongjunchung/mosaics#3]
I'm working on the ENCODE broad peak caller comparison and noticed that some of the output broad peak files output coordinates in exponential notation: 
e.g. in  MOSAICSHMM-wFL/MOSAiCSHMM-wFL-H3K27ME3-GM12878-Rep2_domains.relaxed.broadPeak I see:

chrX      69972048        7e+07   .       0.66427876684357    .52      5.00595640444774        -1      17374

I'm not sure if this file has gone through pre-processing so my apologies if this is not a mosaics error.

**Comment by dongjunchung** [comment]
Thank you for the report. This problem is fixed in ver 2.9.0.
